apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
  namespace: go-api
spec:
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api-server
        image: jvin911/janiths-public-repo:sample-go-api-v3
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
  replicas: 3
  selector:
    matchLabels:
      app: go-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
